name: Souffleur
description: A cross platform remote control for presentations

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: any
  http: ^0.13.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
