name: Create release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-package-msi:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageDmg with Gradle Wrapper
      run: ./gradlew packageMsi
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: ./server/build/compose/binaries/main/msi/*.msi
        name: souffleur.msi

  create-package-dmg:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageDmg with Gradle Wrapper
      run: ./gradlew packageDmg
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: ./server/build/compose/binaries/main/dmg/*.dmg
        name: souffleur.dmg

  create-release:
    runs-on: macos-latest
    needs: [ create-package-msi,  create-package-dmg]
    steps:
    - name: Download dmg
      uses: actions/download-artifact@v3
      with:
        name: souffleur.dmg
    - name: Download msi
      uses: actions/download-artifact@v3
      with:
        name: souffleur.msi
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/Users/runner/work/souffleur/souffleur/*.dmg,/Users/runner/work/souffleur/souffleur/*.msi"
