name: Create release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-package-msi:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageDmg with Gradle Wrapper
      run: ./gradlew packageMsi
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: ./server/build/compose/binaries/main/msi/*.msi
        name: souffleur.msi

  create-package-dmg:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageDmg with Gradle Wrapper
      run: ./gradlew packageDmg
    - name: Codesign executable
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{ secrets.KEYCHAIN_PASSWORD }} build.keychain
        SECURITY_ID=$(security find-identity -v | cut -d '"' -f2 | head -1)
        echo $SECURITY_ID
        /usr/bin/codesign --force -s "$SECURITY_ID" /Users/runner/work/souffleur/souffleur/server/build/compose/binaries/main/app/Souffleur.app -v    
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: ./server/build/compose/binaries/main/dmg/*.dmg
        name: souffleur.dmg

  create-release:
    runs-on: macos-latest
    needs: [ create-package-msi,  create-package-dmg]
    steps:
    - name: Download dmg
      uses: actions/download-artifact@v3
      with:
        name: souffleur.dmg
    - name: Download msi
      uses: actions/download-artifact@v3
      with:
        name: souffleur.msi
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/Users/runner/work/souffleur/souffleur/*.dmg,/Users/runner/work/souffleur/souffleur/*.msi"
