name: Create macOS distribution

on:
  push:

jobs:
  build-gradle-project:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageDmg with Gradle Wrapper
      run: ./gradlew packageDmg